version: '3.8'

services:
  hospital-management-system:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/hospital_db?autoReconnect=true&useSSL=false
      DB_USERNAME: root
      DB_PASSWORD: admin
      JWT_SECRET: 9uGYcAZZA+yCk3UOrgZsXuoadbla5m4PNgobWwfwh3BCw7qsFrpWqrIBBOdhFMF4aBTLM6G03Y7DJ9UoJAZpqg==
      JWT_EXPIRATION: 3600000
      PORT: 8080
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "/app.jar"]

  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hospital_db